version: '3.6'

services:
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    network_mode: "host"
    volumes:
      -  ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    links:
      - influxdb
    ports:
      - '8125:8125'
    depends_on:
      - influxdb 

  


  grafana:
    container_name: grafana
    image: grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=     
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - '3000:3000'
    links:
      - influxdb
    
    depends_on:
      - influxdb





  influxdb:
    container_name: influxdb
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb



volumes:
  grafana_data: {}
  influxdb_data: {}