version: '3.6'
networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    environment:
        INFLUXDB_HTTP_AUTH_ENABLED: "true"
        INFLUXDB_DB: "influx"
        INFLUXDB_ADMIN_USER: "admin"
        INFLUXDB_ADMIN_PASSWORD: "admin"  
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - tig-data:/var/lib/grafana
    networks:
      - tig-net
    ports:
      - '3000:3000'
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "influx"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always
    links:
      - influxdb
    ports:
      - '8125:8125'
    depends_on:
      - "influxdb"
    tty: true
    networks:
      - tig-net
    privileged: true

  








